"""Bearer-token authentication for the CNA API (SEC-001 / ARCH-002).

The API is an internal service the web tier calls; historically it carried no
authentication and relied entirely on being network-private. The AWS appliance
violated that assumption by fronting it with an internet-facing ALB, so a shared
bearer secret is now required on every request.

The token is generated by the appliance Terraform, stored in the cloud vault
(Key Vault / Secrets Manager), and injected as the ``CNA_API_TOKEN`` container
secret into *both* the api and the web containers. The web tier attaches
``Authorization: Bearer <CNA_API_TOKEN>`` to every internal call; this
middleware rejects anything else.

Liveness/readiness probes (``/health``, ``/ready``) are exempt so an
orchestrator can probe the container without holding the secret.
"""

from __future__ import annotations

import hmac
import logging
from collections.abc import Iterable

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import JSONResponse, Response
from starlette.types import ASGIApp

logger = logging.getLogger("cna-api")

# Probe endpoints an orchestrator must reach without the shared secret.
EXEMPT_PATHS: frozenset[str] = frozenset({"/health", "/ready"})


class BearerTokenMiddleware(BaseHTTPMiddleware):
    """Require ``Authorization: Bearer <token>`` on every non-exempt request.

    The comparison uses :func:`hmac.compare_digest` so a wrong token cannot be
    inferred from response timing, and the token itself is never logged.
    """

    def __init__(
        self,
        app: ASGIApp,
        *,
        token: str,
        exempt: Iterable[str] = EXEMPT_PATHS,
    ) -> None:
        super().__init__(app)
        # Compare as bytes: ``hmac.compare_digest`` on ``str`` raises TypeError
        # for non-ASCII input, which an unauthenticated caller could use to
        # force 500s. Starlette decodes header values as latin-1, so encoding
        # the presented value back with latin-1 can never fail.
        self._token = token.encode("utf-8")
        self._exempt = frozenset(exempt)

    async def dispatch(self, request: Request, call_next) -> Response:  # noqa: ANN001
        if request.url.path in self._exempt:
            return await call_next(request)

        header = request.headers.get("Authorization", "")
        scheme, _, presented = header.partition(" ")
        # A missing header yields an empty presented value, which never
        # matches a real token; any non-ASCII byte sequence is simply unequal.
        if scheme.lower() != "bearer" or not hmac.compare_digest(
            presented.encode("latin-1"), self._token
        ):
            return JSONResponse({"detail": "unauthorized"}, status_code=401)

        return await call_next(request)
