"""AES-256-GCM credential crypto — Python twin of apps/cna-web/lib/crypto.ts.

The web tier encrypts secrets it stores in Postgres (cloud credentials, and the
bring-your-own AI API keys on the admin AI Engine page) with AES-256-GCM using
the key in ``CREDENTIAL_ENCRYPTION_KEY`` (base64, exactly 32 bytes). The
serialised form is ``ivB64:tagB64:ciphertextB64`` — 96-bit random IV, 128-bit
auth tag, no additional authenticated data.

This module reads those blobs from the Python services (cna-api). It must stay
byte-compatible with ``lib/crypto.ts``: same env var, same wire format, same
algorithm parameters. ``tests/unit/test_credential_crypto.py`` pins that with a
fixture generated by the Node implementation.

The one wrinkle is tag placement: Node emits the tag separately, while
``cryptography``'s AESGCM expects ``ciphertext || tag`` — the split/concat below
is that translation.
"""

from __future__ import annotations

import base64
import os

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

KEY_ENV = "CREDENTIAL_ENCRYPTION_KEY"

_IV_BYTES = 12
_TAG_BYTES = 16
_KEY_BYTES = 32


class CredentialCryptoError(Exception):
    """Raised when the key is missing/malformed or a blob cannot be decrypted.

    Routers map this to 503: it is an operator configuration problem, not a
    caller error and not an upstream AI failure.
    """


def _key() -> bytes:
    raw = os.environ.get(KEY_ENV, "").strip()
    if not raw:
        raise CredentialCryptoError(f"{KEY_ENV} is not set")
    try:
        key = base64.b64decode(raw, validate=True)
    except (ValueError, TypeError) as exc:
        raise CredentialCryptoError(f"{KEY_ENV} is not valid base64") from exc
    if len(key) != _KEY_BYTES:
        raise CredentialCryptoError(f"{KEY_ENV} must decode to exactly {_KEY_BYTES} bytes")
    return key


def decrypt(blob: str) -> str:
    """Decrypt a value produced by lib/crypto.ts ``encrypt()`` (or :func:`encrypt`)."""
    parts = (blob or "").split(":")
    if len(parts) != 3:
        raise CredentialCryptoError("Invalid ciphertext format")
    try:
        iv, tag, data = (base64.b64decode(p, validate=True) for p in parts)
    except (ValueError, TypeError) as exc:
        raise CredentialCryptoError("Invalid ciphertext encoding") from exc
    if len(iv) != _IV_BYTES or len(tag) != _TAG_BYTES:
        raise CredentialCryptoError("Invalid ciphertext format")
    try:
        plaintext = AESGCM(_key()).decrypt(iv, data + tag, None)
    except InvalidTag as exc:
        raise CredentialCryptoError("Ciphertext is tampered or the key is wrong") from exc
    return plaintext.decode("utf-8")


def encrypt(plaintext: str) -> str:
    """Encrypt to the same ``ivB64:tagB64:ciphertextB64`` form as lib/crypto.ts.

    The Python services only ever *read* stored credentials; this exists for
    tests and parity checks.
    """
    iv = os.urandom(_IV_BYTES)
    sealed = AESGCM(_key()).encrypt(iv, plaintext.encode("utf-8"), None)
    data, tag = sealed[:-_TAG_BYTES], sealed[-_TAG_BYTES:]
    return ":".join(base64.b64encode(part).decode("ascii") for part in (iv, tag, data))


__all__ = ["KEY_ENV", "CredentialCryptoError", "decrypt", "encrypt"]
