"""Unit tests for cna.core.credential_crypto — the Python twin of lib/crypto.ts.

The interop vector below was produced by the TypeScript implementation
(Node `crypto.createCipheriv("aes-256-gcm", ...)`) with a fixed, obviously fake
key and IV, so any drift between the two sides fails here rather than at
runtime in cna-api.
"""

import pytest

from cna.core.credential_crypto import KEY_ENV, CredentialCryptoError, decrypt, encrypt

# 32 bytes of 0x0b — a test fixture, not a credential.
FIXTURE_KEY_B64 = "CwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCws="  # pragma: allowlist secret
# Generated by apps/cna-web/lib/crypto.ts semantics (iv = 000102…0b).
NODE_BLOB = "AAECAwQFBgcICQoL:p06uXPcouNmno+nMmO/COA==:iAHivVSyFlbamd1nGXMW8wfNuGkcoEhsq5j/Q2XQ"  # pragma: allowlist secret
NODE_PLAINTEXT = "sk-test-fixture-not-a-real-key"  # pragma: allowlist secret


@pytest.fixture
def fixture_key(monkeypatch):
    monkeypatch.setenv(KEY_ENV, FIXTURE_KEY_B64)


def test_decrypts_node_generated_blob(fixture_key):
    assert decrypt(NODE_BLOB) == NODE_PLAINTEXT


def test_round_trip(fixture_key):
    blob = encrypt("hello, appliance")
    iv, tag, data = blob.split(":")
    assert iv and tag and data
    assert decrypt(blob) == "hello, appliance"


def test_round_trip_uses_fresh_iv(fixture_key):
    assert encrypt("same") != encrypt("same")


def test_tampered_ciphertext_rejected(fixture_key):
    iv, tag, data = NODE_BLOB.split(":")
    flipped = ("A" if data[0] != "A" else "B") + data[1:]
    with pytest.raises(CredentialCryptoError):
        decrypt(":".join([iv, tag, flipped]))


def test_wrong_key_rejected(monkeypatch):
    monkeypatch.setenv(KEY_ENV, "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=")
    with pytest.raises(CredentialCryptoError):
        decrypt(NODE_BLOB)


@pytest.mark.parametrize("blob", ["", "not-a-blob", "a:b", "a:b:c:d", "!!!:!!!:!!!"])
def test_malformed_blob_rejected(fixture_key, blob):
    with pytest.raises(CredentialCryptoError):
        decrypt(blob)


def test_missing_key_is_config_error(monkeypatch):
    monkeypatch.delenv(KEY_ENV, raising=False)
    with pytest.raises(CredentialCryptoError, match=KEY_ENV):
        decrypt(NODE_BLOB)


@pytest.mark.parametrize("bad", ["not base64!", "c2hvcnQ="])  # invalid / wrong length
def test_malformed_key_is_config_error(monkeypatch, bad):
    monkeypatch.setenv(KEY_ENV, bad)
    with pytest.raises(CredentialCryptoError):
        decrypt(NODE_BLOB)
